### ISSUE TITLE
Uncaught ReferenceError: process is not defined

### ISSUE THREAD

**Issue by briandenicola** [briandenicola/traduire#33]
npm install
npm start

Uncaught ReferenceError: process is not defined
    at ./node_modules/jsonwebtoken/lib/psSupported.js (psSupported.js:3:1)
    at options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
    at ./node_modules/jsonwebtoken/verify.js (verify.js:6:1)
    at options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
    at ./node_modules/jsonwebtoken/index.js (index.js:3:1)
    at options.factory (react refresh:6:1)

**Comment by briandenicola** [comment]
Resolved.
